# Generated by Django 5.2 on 2025-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_remove_producto_categoria_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del cupón', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed_amount', 'Monto Fijo')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valor del descuento (ej. 10 para 10% o S/.10)', max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Indica si el cupón está activo y puede ser usado')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de validez', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de validez', null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para aplicar el cupón', max_digits=10)),
                ('usage_limit', models.IntegerField(default=-1, help_text='-1 para usos ilimitados, de lo contrario, el número máximo de veces que puede ser usado')),
                ('used_count', models.IntegerField(default=0, help_text='Número de veces que el cupón ha sido usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
            },
        ),
    ]
